import type { Metadata } from "next";
import {Poppins} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import {
  getContactInformation,
  getSocialLink,
  getWebsiteInformation
} from "@/controllers/getData";
import {
  ContactInformationResponse,
  SocialLinkResponse,
  WebsiteInformationResponse
} from "@/types";
import Head from "next/head";


const geistMono = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Digital Services",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const res : ContactInformationResponse = await getContactInformation();
  const footerRes: WebsiteInformationResponse = await getWebsiteInformation();
  const socialRes : SocialLinkResponse = await getSocialLink();
  return (
    <html lang="en">
    <Head>
      <meta name="facebook-domain-verification" content="your-verification-code" />
    </Head>
      <body
        className={`${geistMono.className} antialiased`}
        suppressHydrationWarning={true}
      >
        <Navbar data={res} footerRes={footerRes} socialRes={socialRes}/>
        <main className="pt-42">
          {children}
        </main>
      <Footer/>
      </body>
    </html>
  );
}
