import type { Metadata } from "next";
import { Roboto_Mono} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";


const geistMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Digital Services",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.className} antialiased`}
        suppressHydrationWarning={true}
      >
        <Navbar/>
        <main className="pt-36">
          {children}
        </main>
      </body>
    </html>
  );
}
